In [67]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\SHRADDHA\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\SHRADDHA\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\SHRADDHA\AppData\Roaming\Python\Python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\SHRADDHA\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\SHRADDHA\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

### Pandas

Pandas is a powerful Python library used for:

Data analysis
Data cleaning
Working with tables (Excel/CSV data)
Handling large datasets

It is one of the most important libraries in:

Data Science
Machine Learning
AI
Data Analytics

In [68]:
import os
import pandas
import numpy

In [69]:
import pandas as pd
import numpy as np
print(pd.__version__)

3.0.3

In [70]:
df = pd.read_csv(r"C:\data science\pandas\Used_Bikes.csv")

In [71]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [72]:
df.head(5)## to show the first 5 rows of the dataframe Default is 5

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [73]:
df.tail()

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [74]:
df.tail(15)# last sai perint kar deta h

,bike_name,price,city,kms_driven,owner,age,power,brand
32633,Royal Enfield Classic 350cc,87000.0,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
32634,Royal Enfield Thunderbird 350cc,70000.0,Mumbai,13858.0,Second Owner,11.0,350.0,Royal Enfield
32635,Suzuki Zeus 125cc,35000.0,Ahmedabad,11885.0,First Owner,12.0,125.0,Suzuki
32636,KTM RC 390cc,196700.0,Mumbai,13216.0,First Owner,4.0,390.0,KTM
32637,Bajaj Pulsar 150cc,25000.0,Delhi,32588.0,First Owner,9.0,150.0,Bajaj
32638,Yamaha Fazer 25 250cc,123000.0,Kadapa,14500.0,First Owner,4.0,250.0,Yamaha
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [75]:
df.info()# information detha h about the dataframe memeory use vho bhi bhata deta h

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [76]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [77]:
df[["age"]]

        age
0       3.0
1       4.0
2       8.0
3       4.0
4       3.0
...     ...
32643   4.0
32644   9.0
32645   6.0
32646  16.0
32647  13.0

[32648 rows x 1 columns]

In [78]:
df[["brand"]]

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [79]:
df[["age","price"]]

        age     price
0       3.0   35000.0
1       4.0  119900.0
2       8.0  600000.0
3       4.0   65000.0
4       3.0   80000.0
...     ...       ...
32643   4.0   39000.0
32644   9.0   30000.0
32645   6.0   60000.0
32646  16.0   15600.0
32647  13.0   22000.0

[32648 rows x 2 columns]

In [80]:
df[["brand"]]

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [81]:
df["brand"].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [82]:
df["owner"].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [83]:
df["city"].unique()

<StringArray>
[   'Ahmedabad',        'Delhi',    'Bangalore',       'Mumbai',
       'Kalyan',    'Faridabad',       'Mettur',    'Hyderabad',
      'Kaithal',      'Gurgaon',
 ...
  'Bhubaneswar',      'Raiganj', 'Bhilai Nagar',       'Baloda',
     'Anantnag',   'Berhampore',      'Silvasa',       'Hospet',
        'Palai',        'Sidhi']
Length: 443, dtype: str

In [84]:
df["brand"].nunique()# unique value detha h

23

In [85]:
df["brand"].value_counts()# unique value ke count detha h or uske sath unique value bhi detha h  order me detha h

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [86]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [87]:
df.duplicated().sum()# duplicate value ke count detha h

np.int64(25324)

In [88]:
df.drop_duplicates()# duplicate value ko drop kar deta h

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [89]:
df.duplicated().sum()# duplicate value ke count detha h

np.int64(25324)

In [90]:
df.drop_duplicates(inplace=True)# duplicate value ko drop kar deta h or uske sath dataframe me bhi change kar deta h

In [91]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [92]:
df.isna()# missing value ke liye use hota h true false me detha h

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [93]:
df.isnull().sum()# missing value ke count ke liye use hota h

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [94]:
df.dropna(inplace=True)#ye row ko drop kar deta h jisme koi bhi value null ho

In [95]:
# y=mx+c linear regression
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [96]:
#y = mx+c
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [97]:
#y = mx+c
owner_dict = {'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4}

In [98]:
df['owner'] = df['owner'].map(owner_dict)# mapping karna basic javascrip mai use hota hai vaha par same work karta h

In [99]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,1,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,1,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,1,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,1,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,1,5.0,220.0,Bajaj

In [100]:
#df.info()

In [101]:
# yeh par decodeing kiyya ja raha h code ko

In [102]:
#df.drop('city',axis=1,inplace=True)
#df

In [103]:
#df.drop('bike_name',axis=1,inplace=True)# single column drop karna ka liya axis =1 ka use karta or colummn ka liya axis=0 ka use karta h 
#df

In [104]:
# df.drop(['city','bike_name'],axis=1,inplace=True)#multiple column drop karna ka liya k ause kiya jata h 
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,1,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,1,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,1,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,1,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,1,5.0,220.0,Bajaj

In [105]:
#df['brand'].unique()# encoding karna ka liya unique value dekhna jaruri h karta h  dict bane kar encoding ki jati h abhi mena owner ki ecoding ki h

In [106]:
#df["brand"].value_counts(normalize=True) # unique value ke percentage detha h

In [107]:
brands_dict ={'TVS': 1,   'Royal Enfield': 2,         'Triumph': 3,          'Yamaha': 4,
           'Honda': 5,            'Hero': 6,           'Bajaj': 7,          'Suzuki': 8,
         'Benelli': 9,             'KTM': 10,        'Mahindra': 11,        'Kawasaki': 12,
          'Ducati': 13,         'Hyosung': 14, 'Harley-Davidson': 15,            'Jawa': 16,
             'BMW': 17,          'Indian': 18,         'Rajdoot': 19,             'LML': 20,
           'Yezdi': 21,              'MV': 22,           'Ideal': 23,}

In [108]:
#df['brand'] = df['brand'].map(brands_dict)

In [109]:
#df

In [110]:
#df.info()

In [111]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   int64
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), int64(1), str(3)
memory usage: 515.0 KB

In [112]:
df_object=df.select_dtypes(include='object')# select_dtypes ka use karke object type ke column ko select kar sakte h

C:\Users\SHRADDHA\AppData\Local\Temp\ipykernel_41444\1231838636.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_object=df.select_dtypes(include='object')# select_dtypes ka use karke object type ke column ko select kar sakte h

In [113]:
df_object

                                 bike_name       city            brand
0       TVS Star City Plus Dual Tone 110cc  Ahmedabad              TVS
1              Royal Enfield Classic 350cc      Delhi    Royal Enfield
2                     Triumph Daytona 675R      Delhi          Triumph
3                     TVS Apache RTR 180cc  Bangalore              TVS
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition  Bangalore           Yamaha
...                                    ...        ...              ...
9362             Hero Hunk Rear Disc 150cc      Delhi             Hero
9369                   Bajaj Avenger 220cc  Bangalore            Bajaj
9370        Harley-Davidson Street 750 ABS    Jodhpur  Harley-Davidson
9371                 Bajaj Dominar 400 ABS  Hyderabad            Bajaj
9372              Bajaj Avenger Street 220  Hyderabad            Bajaj

[7324 rows x 3 columns]

In [114]:
complete_data =pd.concat([df_object,df_object],axis=1)

In [115]:
complete_data

,bike_name,city,brand,bike_name,city,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,TVS,TVS Star City Plus Dual Tone 110cc,Ahmedabad,TVS
1,Royal Enfield Classic 350cc,Delhi,Royal Enfield,Royal Enfield Classic 350cc,Delhi,Royal Enfield
2,Triumph Daytona 675R,Delhi,Triumph,Triumph Daytona 675R,Delhi,Triumph
3,TVS Apache RTR 180cc,Bangalore,TVS,TVS Apache RTR 180cc,Bangalore,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,Yamaha,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,Yamaha
...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,Hero,Hero Hunk Rear Disc 150cc,Delhi,Hero
9369,Bajaj Avenger 220cc,Bangalore,Bajaj,Bajaj Avenger 220cc,Bangalore,Bajaj
9370,Harley-Davidson Street 750 ABS,Jodhpur,Harley-Davidson,Harley-Davidson Street 750 ABS,Jodhpur,Harley-Davidson
9371,Bajaj Dominar 400 ABS,Hyderabad,Bajaj,Bajaj Dominar 400 ABS,Hyderabad,Bajaj
9372,Bajaj Avenger Street 220,Hyderabad,Bajaj,Bajaj Avenger Street 220,Hyderabad,Bajaj

In [116]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,1,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,1,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,1,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,1,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,1,5.0,220.0,Bajaj

In [117]:
#pandas ka through filtering

df[df['brand']=='TVS']

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,1,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,1,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,1,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
9247,TVS Apache RTR 160cc Rear Disc,70000.0,Ghaziabad,4116.0,1,3.0,160.0,TVS
9307,TVS Apache RTR 160cc,30000.0,Alibag,30000.0,1,10.0,160.0,TVS
9312,TVS Apache RTR 200 4V FI,65450.0,Delhi,9238.0,1,3.0,200.0,TVS
9320,TVS Apache 150cc,20000.0,Hissar,84916.0,1,14.0,150.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,1,2.0,110.0,TVS

In [118]:
# filtering  has three steps:-
#1. condition
#2. apply condition
#3. get the results

In [119]:
TVS_brand =df[df['brand']=='TVS']

In [120]:
TVS_brand['owner'].unique()

array([1, 2, 3])

In [121]:
TVS_first =TVS_brand[TVS_brand['owner']=='First Owner']

In [122]:
df['owner'].unique()

array([1, 2, 3, 4])

In [123]:
df['price'].unique()

array([ 35000., 119900., 600000., ...,  65450.,  11400.,  61483.],
      shape=(1232,))

In [124]:
TVS_first[TVS_first['age']<=2]
TVS_first[TVS_first['kms_driven']<=1500000]

Empty DataFrame
Columns: [bike_name, price, city, kms_driven, owner, age, power, brand]
Index: []

In [125]:
tvvs_brand=df[df['brand']=='TVS']

In [126]:
tvs_under_2=tvvs_brand[tvvs_brand['age']<=2]

In [127]:
tvs_under_2[tvs_under_2['kms_driven']<=20000]

,bike_name,price,city,kms_driven,owner,age,power,brand
193,TVS Apache RTR 160 4V DISC ABS BS6,85000.0,Hyderabad,16000.0,1,2.0,160.0,TVS
360,TVS Apache RTR 160 4V Disc,78700.0,Rudrapur,3710.0,1,2.0,160.0,TVS
401,TVS Apache RTR 200 4V ABS Race Edition,108500.0,Delhi,10000.0,1,2.0,200.0,TVS
425,TVS Apache RTR 160 4V DISC ABS,87000.0,Delhi,7000.0,1,2.0,160.0,TVS
511,TVS Apache RTR 160 4V DRUM ABS,85000.0,Gurgaon,7000.0,1,2.0,160.0,TVS
594,TVS Apache RTR 160 4V DISC ABS,91800.0,Delhi,1050.0,1,2.0,160.0,TVS
664,TVS Apache RTR 160 4V DISC ABS,89000.0,Delhi,3000.0,1,2.0,160.0,TVS
1097,TVS Apache RTR 200 4V Carburetor Race Edition 2.0,93500.0,Bangalore,2500.0,1,2.0,200.0,TVS
1126,TVS Apache RTR 200 4V Dual Channel ABS BS6,130000.0,Bangalore,1300.0,1,1.0,200.0,TVS
1132,TVS Apache RTR 160 4V DISC ABS BS6,98000.0,Jaipur,749.0,1,1.0,160.0,TVS
1171,TVS Apache RR310,200000.0,Mumbai,4400.0,1,2.0,310.0,TVS
1318,TVS Apache RTR 200 4V ABS Race Edition,125000.0,Hyderabad,530.0,1,2.0,200.0,TVS
1514,TVS Apache RTR 160cc Matt Red Rear Disc,76000.0,Delhi,8000.0,1,2.0,160.0,TVS
1678,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,122000.0,Chennai,3100.0,1,2.0,200.0,TVS
1712,TVS Apache RR310 Slipper Clutch,224000.0,Vadodara,3900.0,1,2.0,310.0,TVS
1741,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,98500.0,Delhi,2800.0,1,2.0,200.0,TVS
1762,TVS Apache RTR 160 4V DISC ABS,89135.0,Delhi,2800.0,1,2.0,160.0,TVS
1802,TVS Apache RTR 180cc,88000.0,Gurgaon,900.0,1,2.0,180.0,TVS
2325,TVS Apache RTR 200 4V ABS,92000.0,Mumbai,4500.0,1,2.0,200.0,TVS
2360,TVS Victor 110cc Disc SBT,54000.0,Delhi,6000.0,1,2.0,110.0,TVS
2415,TVS Apache RTR 160 4V DISC ABS,85000.0,Delhi,11496.0,1,2.0,160.0,TVS
3071,TVS Apache RTR 160 4V DISC ABS,94000.0,Ahmedabad,893.0,1,2.0,160.0,TVS
3333,TVS Apache RTR 160 4V Carburetor With Rear Disc,85000.0,Mumbai,6821.0,1,2.0,160.0,TVS
3440,TVS Apache RTR 160 4V Disc,92000.0,Mumbai,14289.0,1,2.0,160.0,TVS
4251,TVS Star City Plus 110cc,51000.0,Ahmedabad,12000.0,1,2.0,110.0,TVS
4367,TVS Apache RTR 160 4V Carburetor,90000.0,Ghaziabad,2672.0,1,2.0,160.0,TVS
5506,TVS Apache RTR 200 4V ABS Race Edition,106000.0,Delhi,1890.0,1,2.0,200.0,TVS
5510,TVS Apache RTR 180cc,90000.0,Ghaziabad,3095.0,1,2.0,180.0,TVS
5557,TVS Apache RTR 200 4V FI,102000.0,Thane,8120.0,1,2.0,200.0,TVS
5805,TVS Apache RTR 200 4V ABS Race Edition,128000.0,Bangalore,4000.0,1,2.0,200.0,TVS
6003,TVS Apache RTR 160 4V Carburetor,90700.0,Delhi,900.0,1,2.0,160.0,TVS
6058,TVS Apache RR310,220000.0,Noida,5432.0,1,2.0,310.0,TVS
6571,TVS Apache RTR 160 4V Carburetor,86000.0,Faridabad,15228.0,1,2.0,160.0,TVS
6787,TVS Apache RTR 200 4V Race Edition 2.0,106000.0,Mumbai,7157.0,1,2.0,200.0,TVS
7055,TVS Sport 100cc,46000.0,Faridabad,6222.0,1,2.0,100.0,TVS
8883,TVS Apache RTR 200 4V ABS Race Edition,120000.0,Mumbai,4442.0,1,2.0,200.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,1,2.0,110.0,TVS

In [128]:
df[(df['brand']=='TVS') & (df['age']<=2) & (df['kms_driven']<=15000)]

,bike_name,price,city,kms_driven,owner,age,power,brand
360,TVS Apache RTR 160 4V Disc,78700.0,Rudrapur,3710.0,1,2.0,160.0,TVS
401,TVS Apache RTR 200 4V ABS Race Edition,108500.0,Delhi,10000.0,1,2.0,200.0,TVS
425,TVS Apache RTR 160 4V DISC ABS,87000.0,Delhi,7000.0,1,2.0,160.0,TVS
511,TVS Apache RTR 160 4V DRUM ABS,85000.0,Gurgaon,7000.0,1,2.0,160.0,TVS
594,TVS Apache RTR 160 4V DISC ABS,91800.0,Delhi,1050.0,1,2.0,160.0,TVS
664,TVS Apache RTR 160 4V DISC ABS,89000.0,Delhi,3000.0,1,2.0,160.0,TVS
1097,TVS Apache RTR 200 4V Carburetor Race Edition 2.0,93500.0,Bangalore,2500.0,1,2.0,200.0,TVS
1126,TVS Apache RTR 200 4V Dual Channel ABS BS6,130000.0,Bangalore,1300.0,1,1.0,200.0,TVS
1132,TVS Apache RTR 160 4V DISC ABS BS6,98000.0,Jaipur,749.0,1,1.0,160.0,TVS
1171,TVS Apache RR310,200000.0,Mumbai,4400.0,1,2.0,310.0,TVS
1318,TVS Apache RTR 200 4V ABS Race Edition,125000.0,Hyderabad,530.0,1,2.0,200.0,TVS
1514,TVS Apache RTR 160cc Matt Red Rear Disc,76000.0,Delhi,8000.0,1,2.0,160.0,TVS
1678,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,122000.0,Chennai,3100.0,1,2.0,200.0,TVS
1712,TVS Apache RR310 Slipper Clutch,224000.0,Vadodara,3900.0,1,2.0,310.0,TVS
1741,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,98500.0,Delhi,2800.0,1,2.0,200.0,TVS
1762,TVS Apache RTR 160 4V DISC ABS,89135.0,Delhi,2800.0,1,2.0,160.0,TVS
1802,TVS Apache RTR 180cc,88000.0,Gurgaon,900.0,1,2.0,180.0,TVS
2325,TVS Apache RTR 200 4V ABS,92000.0,Mumbai,4500.0,1,2.0,200.0,TVS
2360,TVS Victor 110cc Disc SBT,54000.0,Delhi,6000.0,1,2.0,110.0,TVS
2415,TVS Apache RTR 160 4V DISC ABS,85000.0,Delhi,11496.0,1,2.0,160.0,TVS
3071,TVS Apache RTR 160 4V DISC ABS,94000.0,Ahmedabad,893.0,1,2.0,160.0,TVS
3333,TVS Apache RTR 160 4V Carburetor With Rear Disc,85000.0,Mumbai,6821.0,1,2.0,160.0,TVS
3440,TVS Apache RTR 160 4V Disc,92000.0,Mumbai,14289.0,1,2.0,160.0,TVS
4251,TVS Star City Plus 110cc,51000.0,Ahmedabad,12000.0,1,2.0,110.0,TVS
4367,TVS Apache RTR 160 4V Carburetor,90000.0,Ghaziabad,2672.0,1,2.0,160.0,TVS
5506,TVS Apache RTR 200 4V ABS Race Edition,106000.0,Delhi,1890.0,1,2.0,200.0,TVS
5510,TVS Apache RTR 180cc,90000.0,Ghaziabad,3095.0,1,2.0,180.0,TVS
5557,TVS Apache RTR 200 4V FI,102000.0,Thane,8120.0,1,2.0,200.0,TVS
5805,TVS Apache RTR 200 4V ABS Race Edition,128000.0,Bangalore,4000.0,1,2.0,200.0,TVS
6003,TVS Apache RTR 160 4V Carburetor,90700.0,Delhi,900.0,1,2.0,160.0,TVS
6058,TVS Apache RR310,220000.0,Noida,5432.0,1,2.0,310.0,TVS
6787,TVS Apache RTR 200 4V Race Edition 2.0,106000.0,Mumbai,7157.0,1,2.0,200.0,TVS
7055,TVS Sport 100cc,46000.0,Faridabad,6222.0,1,2.0,100.0,TVS
8883,TVS Apache RTR 200 4V ABS Race Edition,120000.0,Mumbai,4442.0,1,2.0,200.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,1,2.0,110.0,TVS

In [129]:
df.query("brand=='TVS' and age<=1 and kms_driven<=150000 and price<=150000")

,bike_name,price,city,kms_driven,owner,age,power,brand
1126,TVS Apache RTR 200 4V Dual Channel ABS BS6,130000.0,Bangalore,1300.0,1,1.0,200.0,TVS
1132,TVS Apache RTR 160 4V DISC ABS BS6,98000.0,Jaipur,749.0,1,1.0,160.0,TVS

In [130]:
# data two parts mai divide
df.drop(['bike_name','city'],axis=1)

         price  kms_driven  owner  age  power            brand
0      35000.0     17654.0      1  3.0  110.0              TVS
1     119900.0     11000.0      1  4.0  350.0    Royal Enfield
2     600000.0       110.0      1  8.0  675.0          Triumph
3      65000.0     16329.0      1  4.0  180.0              TVS
4      80000.0     10000.0      1  3.0  150.0           Yamaha
...        ...         ...    ...  ...    ...              ...
9362   25000.0     48587.0      1  8.0  150.0             Hero
9369   35000.0     60000.0      1  9.0  220.0            Bajaj
9370  450000.0      3430.0      1  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0      1  4.0  400.0            Bajaj
9372   80000.0      7127.0      1  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [131]:
df.drop(['price'],axis=1)

,bike_name,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,10000.0,1,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,48587.0,1,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,Bangalore,60000.0,1,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,Jodhpur,3430.0,1,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,Hyderabad,21300.0,1,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,Hyderabad,7127.0,1,5.0,220.0,Bajaj