In [3]:
import os
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r"C:\data science\pandas\Used_Bikes.csv")

In [5]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [7]:
df[['brand']]

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [8]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [9]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [10]:
df['brand'].nunique()

23

In [11]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [12]:
df.duplicated().sum()# duplicate value ke count ke liye use hota h

np.int64(25324)

In [13]:
df.isnull()

       bike_name  price   city  kms_driven  owner    age  power  brand
0          False  False  False       False  False  False  False  False
1          False  False  False       False  False  False  False  False
2          False  False  False       False  False  False  False  False
3          False  False  False       False  False  False  False  False
4          False  False  False       False  False  False  False  False
...          ...    ...    ...         ...    ...    ...    ...    ...
32643      False  False  False       False  False  False  False  False
32644      False  False  False       False  False  False  False  False
32645      False  False  False       False  False  False  False  False
32646      False  False  False       False  False  False  False  False
32647      False  False  False       False  False  False  False  False

[32648 rows x 8 columns]

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [15]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [16]:
owner_dict = {'First Owner': 1, 'Second Owner': 2, 'Third Owner': 3, 'Fourth Owner Or More': 4}

In [17]:
df['owner']=df['owner'].map(owner_dict)

In [18]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,1,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,1,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,1,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,1,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,1,13.0,150.0,Bajaj

In [19]:
df['owner'].unique()

array([1, 2, 3, 4])

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  int64
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), int64(1), str(3)
memory usage: 2.0 MB

In [21]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,1,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,1,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,1,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,1,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,1,13.0,150.0,Bajaj

In [22]:
brand_dict = {
     'TVS':1, 'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23}

In [23]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,1,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,1,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,1,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,1,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,1,13.0,150.0,Bajaj

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  int64
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), int64(1), str(3)
memory usage: 2.0 MB

In [25]:
obj_val =df.select_dtypes(include='O')

C:\Users\SHRADDHA\AppData\Local\Temp\ipykernel_43180\2170337667.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_val =df.select_dtypes(include='O')

In [26]:
obj_val

                                  bike_name       city          brand
0        TVS Star City Plus Dual Tone 110cc  Ahmedabad            TVS
1               Royal Enfield Classic 350cc      Delhi  Royal Enfield
2                      Triumph Daytona 675R      Delhi        Triumph
3                      TVS Apache RTR 180cc  Bangalore            TVS
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition  Bangalore         Yamaha
...                                     ...        ...            ...
32643                Hero Passion Pro 100cc      Delhi           Hero
32644                  TVS Apache RTR 180cc     Karnal            TVS
32645              Bajaj Avenger Street 220      Delhi          Bajaj
32646             Hero Super Splendor 125cc     Jaipur           Hero
32647                    Bajaj Pulsar 150cc       Pune          Bajaj

[32648 rows x 3 columns]

In [27]:
num_val =df.select_dtypes(exclude='O')

In [28]:
num_val

          price  kms_driven  owner   age  power
0       35000.0     17654.0      1   3.0  110.0
1      119900.0     11000.0      1   4.0  350.0
2      600000.0       110.0      1   8.0  675.0
3       65000.0     16329.0      1   4.0  180.0
4       80000.0     10000.0      1   3.0  150.0
...         ...         ...    ...   ...    ...
32643   39000.0     22000.0      1   4.0  100.0
32644   30000.0      6639.0      1   9.0  180.0
32645   60000.0     20373.0      1   6.0  220.0
32646   15600.0     84186.0      1  16.0  125.0
32647   22000.0     60857.0      1  13.0  150.0

[32648 rows x 5 columns]

In [29]:
complete_Data =pd.concat([obj_val, num_val], axis=1)

In [30]:
complete_Data

,bike_name,city,brand,price,kms_driven,owner,age,power
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,TVS,35000.0,17654.0,1,3.0,110.0
1,Royal Enfield Classic 350cc,Delhi,Royal Enfield,119900.0,11000.0,1,4.0,350.0
2,Triumph Daytona 675R,Delhi,Triumph,600000.0,110.0,1,8.0,675.0
3,TVS Apache RTR 180cc,Bangalore,TVS,65000.0,16329.0,1,4.0,180.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,Yamaha,80000.0,10000.0,1,3.0,150.0
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,Delhi,Hero,39000.0,22000.0,1,4.0,100.0
32644,TVS Apache RTR 180cc,Karnal,TVS,30000.0,6639.0,1,9.0,180.0
32645,Bajaj Avenger Street 220,Delhi,Bajaj,60000.0,20373.0,1,6.0,220.0
32646,Hero Super Splendor 125cc,Jaipur,Hero,15600.0,84186.0,1,16.0,125.0
32647,Bajaj Pulsar 150cc,Pune,Bajaj,22000.0,60857.0,1,13.0,150.0

In [31]:
RoyalEnfield_brand =df[df['brand']=='Royal Enfield']

In [32]:
RoyalEnfield_brand['owner'].unique()

array([1, 2, 3, 4])

In [33]:
RoyalEnfield_first_owner = df[(df['brand']=='Royal Enfield')]

In [34]:
RoyalEnfield_first_owner[RoyalEnfield_first_owner['age']<5]

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,1,3.0,350.0,Royal Enfield
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,1,2.0,500.0,Royal Enfield
62,Royal Enfield Bullet Electra 350cc,107100.0,Delhi,15438.0,2,3.0,350.0,Royal Enfield
73,Royal Enfield Thunderbird X 350cc,150000.0,Bangalore,15000.0,1,3.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
32348,Royal Enfield Bullet Electra 350cc,105000.0,Delhi,20000.0,1,4.0,350.0,Royal Enfield
32367,Royal Enfield Bullet Electra 350cc,105000.0,Delhi,20000.0,1,4.0,350.0,Royal Enfield
32443,Royal Enfield Bullet Electra 350cc,105000.0,Delhi,20000.0,1,4.0,350.0,Royal Enfield
32481,Royal Enfield Bullet Electra 350cc,105000.0,Delhi,20000.0,1,4.0,350.0,Royal Enfield
32614,Royal Enfield Bullet Electra 350cc,105000.0,Delhi,20000.0,1,4.0,350.0,Royal Enfield

In [35]:
df['kms_driven'].unique()

array([17654., 11000.,   110., ..., 48587.,  3430.,  7127.], shape=(3722,))

In [36]:
RoyalEnfield_first_owner[RoyalEnfield_first_owner['kms_driven']<500]

,bike_name,price,city,kms_driven,owner,age,power,brand
850,Royal Enfield Himalayan 410cc Fi ABS,180000.0,Guwahati,200.0,1,2.0,410.0,Royal Enfield
974,Royal Enfield Bullet 350cc,99999.0,Balrampur,55.0,2,15.0,350.0,Royal Enfield
1796,Royal Enfield Himalayan 410cc Fi ABS,166000.0,Guwahati,250.0,1,2.0,410.0,Royal Enfield
1883,Royal Enfield Himalayan 410cc Fi ABS,166000.0,Guwahati,250.0,1,2.0,410.0,Royal Enfield
2740,Royal Enfield Thunderbird 350cc,147000.0,Bangalore,200.0,1,4.0,350.0,Royal Enfield
3523,Royal Enfield Bullet Electra 350cc,112200.0,Bangalore,40.0,1,7.0,350.0,Royal Enfield
3675,Royal Enfield Thunderbird 350cc,147000.0,Bangalore,200.0,1,4.0,350.0,Royal Enfield
6090,Royal Enfield Bullet Electra Twinspark 350CC ABS,127000.0,Mumbai,83.0,1,2.0,350.0,Royal Enfield
7213,Royal Enfield Thunderbird 500cc,154000.0,Udaipur,301.0,1,3.0,500.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,1,2.0,500.0,Royal Enfield
7706,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,1,2.0,500.0,Royal Enfield
8569,Royal Enfield Thunderbird 350cc,140000.0,Delhi,400.0,1,4.0,350.0,Royal Enfield
8770,Royal Enfield Thunderbird 350cc,140000.0,Delhi,400.0,1,4.0,350.0,Royal Enfield

In [37]:
RoyalEnfield_second_owner = df[(df['brand']=='Royal Enfield')]

In [38]:
RoyalEnfield_second_owner[RoyalEnfield_second_owner['age']<4]

,bike_name,price,city,kms_driven,owner,age,power,brand
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,1,3.0,350.0,Royal Enfield
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,1,2.0,500.0,Royal Enfield
62,Royal Enfield Bullet Electra 350cc,107100.0,Delhi,15438.0,2,3.0,350.0,Royal Enfield
73,Royal Enfield Thunderbird X 350cc,150000.0,Bangalore,15000.0,1,3.0,350.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,1,2.0,650.0,Royal Enfield
...,...,...,...,...,...,...,...,...
8597,Royal Enfield Electra 350cc,90000.0,Mumbai,10000.0,1,3.0,350.0,Royal Enfield
8741,Royal Enfield Bullet 500cc,135000.0,Rohtak,6850.0,1,3.0,500.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,1,2.0,350.0,Royal Enfield
9185,Royal Enfield Classic 500cc Dual Disc,163500.0,Azamgarh,13900.0,2,3.0,500.0,Royal Enfield
9308,Royal Enfield Classic 500cc Dual Disc,163500.0,Azamgarh,13900.0,2,3.0,500.0,Royal Enfield

In [39]:
#df['owner'] = df['owner'].map(owner_dict)

In [49]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [40]:

RoyalEnfield_brand=df[df['brand']=='Royal Enfield']

In [47]:
RoyalEnfield_under_2=RoyalEnfield_brand[RoyalEnfield_brand['age']<=2]

In [50]:
RoyalEnfield_under_2[RoyalEnfield_under_2['kms_driven']<=15000]

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,1,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,1,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,1,2.0,410.0,Royal Enfield
157,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,1,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,1,2.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,1,2.0,500.0,Royal Enfield
7706,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,1,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,1,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,1,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,1,2.0,350.0,Royal Enfield

In [51]:
df['owner'].unique()

array([1, 2, 3, 4])

In [52]:
df[(df['brand']=='Royal Enfield')&(df['age']<=2)&(df['kms_driven']<=15000)]

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,1,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,1,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,1,2.0,410.0,Royal Enfield
157,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,1,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,1,2.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,1,2.0,500.0,Royal Enfield
7706,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,1,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,1,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,1,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,1,2.0,350.0,Royal Enfield

In [54]:
df.query("brand=='Royal Enfield'and age<=2")

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,1,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,1,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,1,2.0,410.0,Royal Enfield
157,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,1,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,1,2.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,1,2.0,500.0,Royal Enfield
7706,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,1,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,1,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,1,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,1,2.0,350.0,Royal Enfield

In [55]:
df.drop(['bike_name','city'],axis=1)

          price  kms_driven  owner   age  power          brand
0       35000.0     17654.0      1   3.0  110.0            TVS
1      119900.0     11000.0      1   4.0  350.0  Royal Enfield
2      600000.0       110.0      1   8.0  675.0        Triumph
3       65000.0     16329.0      1   4.0  180.0            TVS
4       80000.0     10000.0      1   3.0  150.0         Yamaha
...         ...         ...    ...   ...    ...            ...
32643   39000.0     22000.0      1   4.0  100.0           Hero
32644   30000.0      6639.0      1   9.0  180.0            TVS
32645   60000.0     20373.0      1   6.0  220.0          Bajaj
32646   15600.0     84186.0      1  16.0  125.0           Hero
32647   22000.0     60857.0      1  13.0  150.0          Bajaj

[32648 rows x 6 columns]

In [57]:
x=df.drop(['price'],axis=1)

In [60]:
##y =mx+c
y=df['price']

In [61]:
y

0         35000.0
1        119900.0
2        600000.0
3         65000.0
4         80000.0
           ...
32643     39000.0
32644     30000.0
32645     60000.0
32646     15600.0
32647     22000.0
Name: price, Length: 32648, dtype: float64

In [59]:
x

,bike_name,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,10000.0,1,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,Delhi,22000.0,1,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,Karnal,6639.0,1,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,Delhi,20373.0,1,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,Jaipur,84186.0,1,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,Pune,60857.0,1,13.0,150.0,Bajaj

In [ ]:
#from sklearn.model_selection import train_test_split

In [62]:
# data ko save ka liya 
df.to_csv("clear_bike_data.csv")